#!/usr/bin/env python3
"""Turn VMS probe results into a config.site fragment for the host configure run.

Usage: cfgprobe_site.py <configure> <crtl_modules.txt> <probe-log>... > probed.site

Each probe log holds 'RESULT <cachevar> yes|no' lines from vms_cfgprobe.com.
When several logs are given (one per architecture) they must agree; any
disagreement is reported and the check is left out so that it has to be
settled explicitly in vms-manual.site.

Also emits gl_cv_next_<header> values: VSI C has no #include_next, so
gnulib's wrapper headers reach the CRTL header through the text-library form
'#include MODULE', where MODULE is the header's basename in DECC$RTLDEF.TLB.
"""
import re
import sys


def read_results(path):
    res = {}
    for line in open(path, encoding='latin-1'):
        m = re.match(r'RESULT (\S+) (yes|no)\s*$', line.strip())
        if m:
            res[m.group(1)] = m.group(2)
    return res


def main():
    if len(sys.argv) < 4:
        sys.exit(__doc__)
    configure = open(sys.argv[1], encoding='latin-1').read()
    modules = {l.strip() for l in open(sys.argv[2])
               if l.strip() and not l.startswith('#')}
    logs = sys.argv[3:]
    results = [read_results(p) for p in logs]
    if not all(results):
        sys.exit('cfgprobe_site.py: a probe log has no RESULT lines')

    out = ['# Generated by tools/cfgprobe_site.py from VMS probe runs:']
    out += ['#   %s (%d results)' % (p, len(r)) for p, r in zip(logs, results)]
    out.append('# Do not edit; override in vms-manual.site instead.')
    out.append('')
    conflicts = []
    for var in sorted(set().union(*results)):
        vals = {r.get(var) for r in results}
        if len(vals) != 1 or None in vals:
            conflicts.append(var)
            continue
        out.append('%s=%s' % (var, vals.pop()))

    out.append('')
    out.append('# No #include_next on VSI C: wrap CRTL headers via text-library modules.')
    out.append('gl_cv_have_include_next=no')
    for var in sorted(set(re.findall(r'\bgl_cv_next_([a-z0-9_]+)_h\b', configure))):
        # sys_stat -> STAT, netinet_in -> IN; module key is the header basename.
        module = var.split('_')[-1].upper()
        if module in modules:
            out.append("gl_cv_next_%s_h=%s" % (var, module))
    for var in conflicts:
        out.append('# CONFLICT between architectures, settle in vms-manual.site: %s' % var)
    print('\n'.join(out))
    if conflicts:
        print('cfgprobe_site.py: %d conflicting results: %s' % (len(conflicts), ' '.join(conflicts)),
              file=sys.stderr)


if __name__ == '__main__':
    main()
