#!/usr/bin/env python3
"""Write vms/sources.mms: object lists and one explicit MMS rule per object.

Usage: gen_mms.py <ccflags.txt> <lib-sources.txt> <src-sources.txt> <extra-sources.txt> > sources.mms

Source paths are relative to lib/, src/ or the tree root (extra).  Objects go
to $(OBJ), which descrip.mms sets per architecture.  VSI C accepts a single
/DEFINE, so the defines from ccflags.txt are split out into CC_DEFS for
descrip.mms to merge with its own.
"""
import os
import re
import sys


def vms_dir(path):
    """'lib/malloc' -> '[.LIB.MALLOC]'"""
    parts = [p for p in path.split('/') if p and p != '.']
    return '[.' + '.'.join(p.upper() for p in parts) + ']' if parts else '[]'


def read_list(path):
    return [l.strip() for l in open(path) if l.strip() and not l.startswith('#')]


def main():
    if len(sys.argv) != 5:
        sys.exit(__doc__)
    flags = open(sys.argv[1]).read().strip()
    m = re.search(r'/DEFINE=\(([^)]*)\)', flags, re.I)
    defs = m.group(1) if m else ''
    qual = re.sub(r'/DEFINE=\([^)]*\)', '', flags, flags=re.I)

    groups = [('LIB', 'lib', read_list(sys.argv[2])),
              ('SRC', 'src', read_list(sys.argv[3])),
              ('EXTRA', '', read_list(sys.argv[4]))]
    out = ['! Generated by tools/gen_mms.py - do not edit', '',
           'CC_QUAL = ' + qual, 'CC_DEFS = ' + defs, '']
    rules = []
    for macro, base, srcs in groups:
        objs = []
        for s in srcs:
            full = os.path.join(base, s) if base else s
            stem = os.path.splitext(os.path.basename(s))[0]
            obj = '$(OBJ)%s.OBJ' % stem
            objs.append(obj)
            rules += ['%s : %s%s' % (obj, vms_dir(os.path.dirname(full)), os.path.basename(full)),
                      '\t$(CC) $(CFLAGS) /OBJECT=$(MMS$TARGET) $(MMS$SOURCE)', '']
        out.append('%s_OBJS = %s' % (macro, ', -\n\t'.join(objs) if objs else ''))
        out.append('')
    print('\n'.join(out + rules))


if __name__ == '__main__':
    main()
