$! VMS_CFGPROBE.COM - run the configure probes generated by cfgprobe_gen.py
$!
$! P1 = directory holding MANIFEST.TXT and the Pnnnn.C probe programs
$! P2 = C compiler qualifiers (the same ones the real build uses)
$!
$! Writes one line per check to SYS$OUTPUT:  RESULT <cachevar> yes|no
$!
$ set noon
$ say = "write sys$output"
$ dir = p1
$ ccq = p2
$ set default 'dir'
$ say "CCQUAL ", ccq
$ open/read man manifest.txt
$loop:
$ read/end=done man line
$ id = f$element(0, " ", line)
$ kind = f$element(1, " ", line)
$ dolink = f$element(2, " ", line)
$ var = f$element(3, " ", line)
$ define/user sys$output nl:
$ define/user sys$error nl:
$ cc 'ccq' /nolist/object=cfgp_tmp.obj 'id'.c
$ sev = $severity
$ ok = (sev .ne. 2) .and. (sev .ne. 4)
$ if ok .and. dolink .eqs. "Y"
$ then
$   define/user sys$output nl:
$   define/user sys$error nl:
$   link/executable=cfgp_tmp.exe cfgp_tmp.obj
$   ok = $severity .eq. 1
$ endif
$ if ok
$ then say "RESULT ", var, " yes"
$ else say "RESULT ", var, " no"
$ endif
$ goto loop
$done:
$ close man
$ if f$search("cfgp_tmp.*") .nes. "" then delete/nolog cfgp_tmp.*;*
$ say "=== DONE"
